[package]
name = "runty8-core"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { version = "*", default-features = false }
# include_dir = "0.7.3"
paste = "1.0.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "*", features = ["js"] }
