[package]
name = "runty8-core"
version = "0.1.0"
edition = "2021"

[dependencies]
display_utils = "0.4.0"
itertools = { version = "*", default-features = false }
math = { git = "https://github.com/nagisa/math.rs" }
# include_dir = "0.7.3"
paste = "1.0.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "*", features = ["js"] }
